var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                      ",
   "                                                                                      ",
   "                                                    o                                 ",
   "                                 o                  xx     o      xxx                x ",
   "                               xxxxxxxxxxx o        *      xx   xxx!xxx              x ",
   "                               x!!!!!!!!!xxxx                  xx!!!!!xx      o      x ",
   "                             o x!!!!!!!!!!!xxxx                 xxx!xxx              x ",
   "                            xxxxvvxxxxxxxx!!!!!v                 xxvxx      xxxx",
   "                                         xxxxxx    xxx                      xxxx",
   "  xx                    o                x                 o                 xx ",
   "  x                   xxxxx    *         x o              xxx                xx ",
   "  x           o                          xxxx                  xx            xx ",
   "  x          xxxx         ^                                                  xx ",
   "  x  @  o                                                          o        x        ",
   "  xxxxxxxxx!!!!!!!!!xxxxxxxxxxx   xxxxxxxxxxxxxxxxxxx   x   xxxxxxxxxxxxxxxxxx        ",
   "          xxxxxxxxxxx         x   x                 x!!!x!!!!x                        ",
   "                              x!!!x                 xx!!!!!xxx                        ",
   "                              x!!!x                  x!!!!!x                          ",
   "                              xxxxx                  xxxxxxx                          ",
   "                                                                                      ",
   "                                                                                      "],
  ["                                      x!!x                        xxxxxxx                                    x!x  ",
   "                                      x!!x                     xxxx     xxxx                                 x!x  ",
   "                                      x!!xxxxxxxxxx           xx           xx                                x!x  ",
   "                                      xx!!!!!!!!!!xx         xx             xx                               x!x  ",
   "                                       xxxxxxxxxx!!x         x       o                                       x!x  ",
   "                                                xx!x         x     o   o                                ooo xx!x  ",
   "                                                 x!x         x                                xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x     x   x                        !!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            xxxxxxx                  ",
   "                                                               xxxx!xvxxxxxx                  xx                  ",
   "                                               x                 xxxx xxxxxxxxxxxxxx         xxx                  ",
   "                                               x                                   x       xxxxx                  ",
   "                                               x                 *                 x         x                    ",
   "                         *                     x                                   xx        x                    ",
   "                         ^                     x                                             x                    ",
   "                                               x     xx    xx   xx       xxxxxxxxxx         xx                  ",
   "            *         xxx     xxx   xxx        xx    x!!!!!!!!!!!!!!xx   x!v!!!!!!!xx        x                    ",
   "                      xxx       x   x          x     xxxxxxxxxxxxxxxxx   xx xxxxxxx          x                    ",
   "              o                 x o x          x     xx               x   x   x               x                    ",
   "     @       xxx                x   x          x     x               x   x   x              xx                   ",
   "    xxx      xxx                x o x         x     x               x           xxxxxx      x                    ",
   "    x x                        xx   xx         x     x               x     o    xxxx         x                    ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!xx     xx!!!!!!!!xx     x!!!!!!!!!!     x          xxxx         xx                   ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxxxxx       xx                    ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!x                      xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!x    o        o       xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["            x    x      x   x    x     x             xxxx                                                     ",
   "                 |          |                         xxx                                                    ",
   "                                                       xx                                                     ",
   "            o          o        o         o             xxxxxxxxxxxx                                           ",
   "                                                                  x                                   ",
   "         @                                                        x                                          ",
   "         xx    xx   xx   xx   xx   xx   xx   xx   xx  xxxxxxxxxx  xxxxxx                                    ",
   "                                                           xx!!x  x!!!!x                                      ",
   "            |           |        |     |                   xx!!x ox!!!!x                                      ",
   "            x    x      x   x    x     x                   xx!!x  x!!!!x                                      ",
   "                                                           xx!!x ox!!!!x                                      ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!x  x!!!!x                           x          ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!x ox!!!!xx                                     ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!x  x!!!!xx                                     ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!x ox!!!!x                                      ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!x  x!!!!x                                 o    ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!x  x!!!!x                                xxx   ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx    xxxxx                             o        ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                ^*                   xxx       ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                *^  o            o            ",
   "                                                              x    x                           xxx            ",
   "                                                              x o  x         o       =    o      =    =       ",
   "                                                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx                                                                                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x                           x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx                                                                x  ",
   "  x      x          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                                                                                                  x x x       ",
   "                                                                                                  xxx x       ",
   "                   xxx                                                                                x       ",
   "       !     !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x=    x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !     !                                               xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "                         xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                                                                                x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                           x                   *                x           ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                             o                   ",
   "  x         xxxxxxxxxxxxx   xxxxxxxxx o xx                                    o     o     x                   ",
   "  x        xxxxxx |     xxxxx     | xxxxx                 *^                  x     x                         ",
   "  x  @              o           o                                o                                            ",
   "  xxxxxxx             |       |               xxxxx       xx     xx     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x                     xxx                                   ",
   "        x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;